
module.exports = {
	DB_PORT:21818,

	//正式服务器
	DB_HOST:'127.0.0.1',
	RET_OK:0,
	RET_WARN:-1,
	RET_ERR:-2,
	RET_OTHER:1,

	UPLOAD_INTERVAL:5,//上传条件：时间间隔
	UPLOAD_DISTANCE:50,//上传条件：移动距离
	HB_INTERVAL:5,//心跳的时间间隔

	LOGIN_PHONE:'1',
	LOGIN_WEIXIN:'2',
	LOGIN_QQ:'3',
	LOGIN_WEIBO:'4',
	LOGIN_TOURIST:'5',

	MODE_POWER_SAVE:1,
	MODE_REGULAR:2,
	MODE_ACCURATE:3,
	
	ERROR_INPUT_MSG:'传入参数不能为空或者格式不对应',
};
